### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by ResqDiver1317** [sandalle/minecraft_bigreactor_control#82]
I used this program back in our 1.7.10 custom modpack to manage my reactors/turbines and really liked it. We are now running a 1.10.2 custom modpack with ExtremeReactors and I'm adding ComputerCraft 1.80-pr0-build10 which according to info in the discussion on their curseforge page, should work in 1.10.2 (crossing fingers here). I'm wondering if this script is still going to work in this newer environment or not. I'm working with one of our other players and we are currently setting up our reactor/turbine system and would really like to be able to control it like we used to.

**Comment by sandalle** [comment]
I haven't tried it on any modpack since 1.7.10. I have 1.10.2 and 1.11.2 modpacks with Extreme Reactors in them, though I dropped it from my 1.12.2 modpacks, which I can try my scripts on. I might have Open Computers on those modpacks instead of Computer Craft, but I can add the latter for testing when I have time.

**Comment by mechaet** [comment]
Can confirm it works in 1.12.2 with Extreme Reactors and ComputerCraft, I just tested it using the All The Mods 3 modpack.

**Comment by sandalle** [comment]
Thank you for testing @mechaet . :)
